W3D3_Web_17071623/Models/ErrorViewModel.cs
using System;

namespace W3D3_Web_17071623.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

W3D3_Web_17071623/Models/HotelBoeking.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace W3D3_Web_17071623.Models
{
    public class HotelBoeking
    {
        public int HotelBoekingId { get; set; }
        public DateTime Aankomst { get; set; }
        public DateTime Vertrek { get; set; }        
    }
}

W3D3_Web_17071623/Controllers/HotelBoekingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using W3D3_Web_17071623.Models;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace W3D3_Web_17071623.Controllers
{   

    public class HotelBoekingController : Controller
    {
        public static List<HotelBoeking> BoekingsList = new List<HotelBoeking>();

        // GET: /<controller>/
        public IActionResult Index()
        {   
            return View(BoekingsList);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(HotelBoeking boeking)
        {
            if(!BoekingsList.Contains(boeking))
            {
                BoekingsList.Add(boeking);
            }

            return View("Details", boeking);
        }
        

        public IActionResult Details(int id)
        { 
            return View(BoekingsList[id]);
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            return View(BoekingsList[id]);
        }

        [HttpPost]
        public IActionResult Edit(int id, HotelBoeking nieuweBoeking)
        {
            if (BoekingsList[id] != null)
            {
                BoekingsList[id].Aankomst = nieuweBoeking.Aankomst;
                BoekingsList[id].Vertrek = nieuweBoeking.Vertrek;
            }

            return RedirectToAction("Index");
        }

    }
}

W3D3_Web_17071623/Views/HotelBoeking/Create.cshtml
@model HotelBoeking

@{
}

<h2>Boeking</h2>

<form action="/HotelBoeking/Create" method="post">
    Aankomst: <input type="date" name="Aankomst" />
    Vertrek: <input type="date" name="Vertrek"/>
    <input type="submit" value="Boek"/>
</form>

W3D3_Web_17071623/Views/HotelBoeking/Details.cshtml
@model HotelBoeking

@{
}

<h2>Bedankt voor het boeken van een hotelkamer!</h2>
<h3>Hieronder kunt u de details vinden van uw vertrek en aankomst</h3>

<div>Uw aankomst: @Model.Aankomst.ToShortDateString()</div>
<div>Uw vertrek: @Model.Vertrek.ToShortDateString()</div>

<a asp-area="" asp-controller="HotelBoeking" asp-action="Index">Terug naar Index</a>

W3D3_Web_17071623/Views/HotelBoeking/Edit.cshtml
@model HotelBoeking

@{
}

<h2>Edit</h2>

<form action="/HotelBoeking/Edit" method="post">
    Aankomst: <input type="date" value ="@Model.Aankomst" name="Aankomst" />
    Vertrek: <input type="date" value="@Model.Vertrek" name="Vertrek" />
    <input type="submit" value="Boek" />
</form>

W3D3_Web_17071623/Views/HotelBoeking/Index.cshtml
@model List<HotelBoeking>
@{
}

<h2>Boek een hotel!</h2>

<div class="container">
    <div class="row">
        <div class="col-lg-3">
            <b>Vertrek</b>
        </div>
        <div class="col-lg-3">
            <b>Aankomst</b>
        </div>
        <div class="col-lg-3">
            <b>Actie</b>
        </div>
    </div>
    @foreach (HotelBoeking boeking in Model)
    {
    <div class="row">
        <div class="col-lg-3">
            @boeking.Aankomst.ToShortDateString()
        </div>
        <div class="col-lg-3">
            @boeking.Vertrek.ToShortDateString()
        </div>
        <div class="col-lg-3">
            <a asp-area="" asp-controller="HotelBoeking" asp-action="Details">Details</a> |
            <a asp-area="" asp-controller="HotelBoeking" asp-action="Edit" asp-route-id="@boeking.HotelBoekingId".>Edit</a> 
        </div>
    </div>   
    }
</div>

<br>
<a asp-area="" asp-controller="HotelBoeking" asp-action="Create">Boek een kamer!</a>

W3D3_Web_17071623/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HotelBoeking</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="HotelBoeking" asp-action="Index" class="navbar-brand">HotelBoeking</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="HotelBoeking" asp-action="Index">Home</a></li>                    
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - W3D3_Web_17071623</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>